### ISSUE TITLE
Logging outputs of Hooks

### ISSUE THREAD

**Issue by facocalj** [edio/randrctl#10]
Heya,

Is there any way to log the output of commands in the hooks?

I've tried to pipe them into a file, but then the commands don't appear to be executed at all

**Comment by edio** [comment]
Seems to be working for me.

In `prior_switch` hook I redirect output to a specified file

```
[~]$ cat ~/.config/randrctl/config.ini                                                                                                                                                        
[hooks]
prior_switch = echo "hello" > /tmp/randrctltest && echo "world" >> /tmp/randrctltest
post_switch = sh ~/.fehbg && /usr/bin/notify-send -u low "randrctl" "switched to $randr_profile"
post_fail = /usr/bin/notify-send -u critical "randrctl error" "can't switch to $randr_profile\n$randr_error"
[~]$ randrctl auto                                                                                                                                                                            
[~]$ cat /tmp/randrctltest                                                                                                                                                                    
hello
world
```

Let me know if this helps.

**Comment by facocalj** [comment]
Hi @edio ,

You are right, it works properly. The issue was not the piping, but rather the line break between commands

Something like:
```
prior_switch = \
 /usr/bin/killall -SIGSTOP -q i3 && \
 /usr/bin/killall -SIGKILL -q compton 
```
Returns:
```
[ ~]$  randrctl auto 
/bin/sh: line 2: \: command not found
/bin/sh: line 2: \: command not found

```
Whilst:
```
prior_switch =  /usr/bin/killall -SIGSTOP -q i3 && /usr/bin/killall -SIGKILL -q compton 
```
Works like a charm

Is there any way to break lines in the hooks?

**Comment by edio** [comment]
I'd offer to define hook in an executable script and point randrctl to it

```
prior_switch = ~/.config/randrctl/hooks/priorswitch
```

**Comment by facocalj** [comment]
Hi @edio,

That did the drill, now everything is working. Thanks a lot!

However, shouldn't _randrctl_ support line breaks natively? Or is it a limitation of ConfigParser?

**Comment by edio** [comment]
@facocalj  INI file does not support multi-line values, afaik.

randrctl has a dependency to pyyaml since 1.4.0, so it's be possible to introduce yaml config instead of ini (which, I believe, we should eventually do).

**Comment by facocalj** [comment]
@edio, 
I made the changes in #11

**Comment by facocalj** [comment]
Now that we support multi line hooks, can you close the issue?
