### ISSUE TITLE
Question: Removal of --system

### ISSUE THREAD

**Issue by seglberg** [edio/randrctl#20]
Thank you for this awesome utility - I've been using it for some time.

I recently tried upgrading to the latest version and noticed that the `--system` flag was removed. Was this intentional? I relied on storing profiles in `/etc` so that I could call `randrctl` from my login manager to setup the screens on startup (e.g. LightDM's `display-setup-script`).

**Comment by edio** [comment]
I was not aware anyone is using it. So decided to remove it and simplify code a little bit.
Should not be hard to get it back though.

I'll try to take a look into that as soon as i have time (hopefully this weekend).

**Comment by edio** [comment]
@seglberg , could you please elaborate, how exactly `randrctl --system` is used in your case?

Do you only use `/etc` to make profiles available for the root user (or whoever owns lightdm process)?Would it work for you if I added an option to set home directory for randrctl?

I would envision something like
```
# randrctl --dir /home/seglberg/.config/randrctl
```
or if you want to make your profiles readable not only for root
```
# chown a+r -R /home/seglberg/.config/randrctl
# ln -s  /home/seglberg/.config/randrctl /etc/randrctl
# randrctl --dir /etc/randrctl
```

**Comment by seglberg** [comment]
A dir option would be just fine, as you mentioned. Honestly, makes it a bit
more flexible.

I'm just looking to store my profiles outside of my home directory for
different processes to use (which aren't always running as my own user).
Thus your symlink example would work great.

**Comment by edio** [comment]
I don't have time to work on this atm. Likely it will only happen after the New Year.
Any help with this would be highly appreciated.
