### ISSUE TITLE
1.9.0 not released to pypi

### ISSUE THREAD

**Issue by palfrey** [edio/randrctl#25]
https://pypi.org/project/randrctl/ still has 1.8.2

**Comment by edio** [comment]
Hi, @palfrey. Thanks a lot for reporting this, I've just uploaded the package to PyPI
https://pypi.org/project/randrctl/1.9.0/

Closing, but please feel free to reopen if there are any issues.

**Comment by palfrey** [comment]
Thanks. All looks good to me.
